rptest: refresh gcp tokens when they expire
We've hit some cases in which tests run for longer than usual and we
get failures during diagnostics collection. GCP guarantees that these
tokens have between 5 minutes and 1 hour of lifetime. Clearly that can't
be enough. I'm not sure why we haven't seen this type of failure more
widely though. Anyway, respect the expiration duration given the
metadata server from now on.

Error example:

```
botocore.exceptions.ClientError: An error occurred (AuthenticationRequired) when calling the ListObjectsV2 operation: Authentication required.
```