rptest: set log_segment_size_min in delayed_translation_test
We would previously see test timeouts like the following:

```
TimeoutError('Failed waiting for all partitions to be GCed')
Traceback (most recent call last):
  File "/opt/.ducktape-venv/lib/python3.10/site-packages/ducktape/tests/runner_client.py", line 381, in _do_run
    data = self.run_test(self.test_runner_timeout)
  File "/opt/.ducktape-venv/lib/python3.10/site-packages/ducktape/tests/runner_client.py", line 453, in run_test
    return self.test_context.function(self.test)
  File "/opt/.ducktape-venv/lib/python3.10/site-packages/ducktape/mark/_mark.py", line 443, in wrapper
    return functools.partial(f, *args, **kwargs)(*w_args, **w_kwargs)
  File "/home/ubuntu/redpanda/tests/rptest/services/cluster.py", line 246, in wrapped
    r = f(self, *args, **kwargs)
  File "/home/ubuntu/redpanda/tests/rptest/tests/datalake/delayed_translation_test.py", line 161, in test_basic
    log_starts = self.produce_until_result(
  File "/home/ubuntu/redpanda/tests/rptest/tests/datalake/delayed_translation_test.py", line 108, in produce_until_result
    return wait_until_result(*args, **kwargs)
  File "/home/ubuntu/redpanda/tests/rptest/util.py", line 128, in wait_until_result
    wait_until(wrapped_condition, *args, **kwargs)
  File "/opt/.ducktape-venv/lib/python3.10/site-packages/ducktape/utils/util.py", line 57, in wait_until
    raise TimeoutError(err_msg() if callable(err_msg) else err_msg) from last_exception
ducktape.errors.TimeoutError: Failed waiting for all partitions to be GCed
```

It seems that in the test we don't get to locally GC all the partitions
because several of the first segments of the partitions are still
active, and we'll only remove inactive segments. Upon further inspection
we set log_segment_size, but not log_segment_size_min, so our segments
end up much closer to 1MiB (the default) rather than 10KiB. This commit
updates the test to also set log_segment_size_min.