rptest: update Iceberg catalog to work with manual CDT
I found that when deploying CDT manually I would hit an error in Spark's
Iceberg REST client complaining about:

```
java.lang.NullPointerException: The URI scheme of endpointOverride must not be null
```

Comparing the configuration against an automated CDT run, the endpoint
appears to be not set in automated CDT. It's unclear to me exactly why
that is, but this commit hacks around the issue.

(cherry picked from commit 3b7da61def1dc90a2a70ebc8dedaab3e1a4265a9)