storage: do not index past uint32_t::max
CONFLICT:
- make_random_batches() returns non-futurized in thie branch
- test case above the new tests doesn't exist in this branch

Once values begin coming in whose deltas are beyond uint32_t::max, the
index is basically unusable (queries have somewhat undefined behavior).

This updates the index to skip adding values if the offset delta would
overflow.

Prior to this change, one included test would fail with:

```
src/v/storage/tests/log_segment_reader_test.cc(376): error: in "test_ghost_read_with_index_overflow": check first.last_offset() == model::offset{100} has failed [2147483746 != 100]
src/v/storage/tests/log_segment_reader_test.cc(377): error: in "test_ghost_read_with_index_overflow": check first.header().type == model::record_batch_type::raft_data has failed [batch_type::ghost_batch != batch_type::raft_data]
```

This test failing means that a recovery from such an overflowed topic
could end up missing some batches.

Another included test would fail, this one relying on behavior addressed
by https://github.com/redpanda-data/redpanda/pull/25974 to cause
trouble:

```
src/v/storage/tests/log_segment_reader_test.cc(382): error: in "test_read_with_index_overflow_base": check first.base_offset() == model::offset{uint32_max} has failed [8589934591 != 4294967295]
src/v/storage/tests/log_segment_reader_test.cc(383): error: in "test_read_with_index_overflow_base": check first.last_offset() == model::offset{uint32_max} has failed [8589934591 != 4294967295]
```

This test failing means that a compaction could attempt to read a whole
segment but only get a part of a segment, and we could end up removing
batches incorrectly.

Just an interesting tidbit, these tests pass if using the batch cache.
This is relevant as we have been chasing issues with the
__consumer_offsets topic, which does not use the batch cache.

(cherry picked from commit 0ed8d64254eb61b2cb8ce5197b6c71b3f1191fef)