dev_cluster: add missing bazel deps
Otherwise it fails with the following error:

```
$ bazel run //tools:dev_cluster -- --nodes 1
INFO: Invocation ID: 9b74fcf5-81a6-4289-95a6-b168ab197127
INFO: Analyzed target //tools:dev_cluster (3 packages loaded, 228 targets configured).
INFO: Found 1 target...
Target //tools:dev_cluster up-to-date:
  bazel-bin/tools/dev_cluster
INFO: Elapsed time: 133.891s, Critical Path: 131.97s
INFO: 52 processes: 8 internal, 44 linux-sandbox.
INFO: Build completed successfully, 52 total actions
INFO: Running command line: bazel-bin/tools/dev_cluster -e src/v/redpanda/redpanda -o tools/minio.exe --nodes 1
Traceback (most recent call last):
  File "/home/nv/.cache/bazel/_bazel_nv/c70040263e6c93a9af1759e544db996d/execroot/_main/bazel-out/k8-fastbuild/bin/tools/dev_cluster.runfiles/_main/tools/dev_cluster.py", line 29, in <module>
    import aioboto3
  File "/home/nv/.cache/bazel/_bazel_nv/c70040263e6c93a9af1759e544db996d/execroot/_main/bazel-out/k8-fastbuild/bin/tools/dev_cluster.runfiles/rules_python~~pip~python_deps_312_aioboto3/site-packages/aioboto3/__init__.py", line 5, in <module>
    from aioboto3.session import Session
  File "/home/nv/.cache/bazel/_bazel_nv/c70040263e6c93a9af1759e544db996d/execroot/_main/bazel-out/k8-fastbuild/bin/tools/dev_cluster.runfiles/rules_python~~pip~python_deps_312_aioboto3/site-packages/aioboto3/session.py", line 9, in <module>
    import boto3.session
ModuleNotFoundError: No module named 'boto3'
```