`rptest`: deflake `CompactionGapsTest`
This test began flaking after adjacent compaction over ranges was merged.

The test expects to see a certain number of segments produced, and adjacent
compaction over ranges is often able to outpace the rate of segment production
in keeping the number of segments down, leading to a timeout like

```
AssertionError: Unable to reach segment count 8 in 180s, current count 6
```

Set `log_compaction_merge_max_ranges=1` and `log_compaction_merge_max_segments_per_range=2`
to revert adjacent compaction to its previous, less effective behavior
(one pair of segments combined per sliding window round) in order to prevent
it from outpacing the producer.